[versions]
agp = "8.13.2"
camerax = "1.5.1"
coil = "2.7.0"
crashlytics = "3.0.6"
gms = "4.4.4"
hilt = "2.57.2"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
navigation = "2.9.6"
retrofit = "3.0.0"
room = "2.8.4"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.12.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version = "1.3.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.2.0" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.10.0" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version = "1.2.1" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version = "2.11.0" }

# billing
googleplay-billingclient = { group = "com.android.billingclient", name = "billing-ktx", version = "8.1.0" }
rustore-billingclient = { group = "ru.rustore.sdk", name = "billingclient", version = "9.0.1" }

# coil
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-base = { group = "io.coil-kt", name = "coil-base", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

# google drive
# mvnrepository.com/artifact/com.google.api-client/google-api-client-android
# javadoc.io/doc/com.google.apis/google-api-services-drive/latest/index.html
# mvnrepository.com/artifact/com.google.http-client/google-http-client-gson
# mvnrepository.com/artifact/com.google.android.gms/play-services-auth
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version = "2.8.1" }
google-api-services-drive = { group = "com.google.apis", name = "google-api-services-drive", version = "v3-rev20240628-2.0.0" }
google-http-client-gson = { group = "com.google.http-client", name = "google-http-client-gson", version = "2.0.2" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "21.4.0" }

# google firebase
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "34.6.0" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

# google flexbox
google-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }

# google material
google-material = { group = "com.google.android.material", name = "material", version = "1.13.0" }

# google mlkit
google-mlkit = { group = "com.google.mlkit", name = "barcode-scanning", version = "17.3.0"}

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# image cropper
image-cropper = {group = "com.vanniktech", name = "android-image-cropper", version = "4.6.0"}

# kotlin csv
kotlin-csv = { module = "com.github.doyaaaaaken:kotlin-csv-jvm", version = "1.10.0"}

# okhttp and retrofit
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "5.3.2" }
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-retrofit2-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# yandex
yandex-authsdk = { group = "com.yandex.android", name = "authsdk", version = "3.1.4" }

# zxing
zxing-core = { group = "com.google.zxing", name = "core", version = "3.5.4"}

# test
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version = "1.3.0" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1"}
